"""add_hosting_name_column

Revision ID: 78f9b7cef7e2
Revises: 63daa3c4351e
Create Date: 2025-06-14 14:58:04.986892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78f9b7cef7e2"
down_revision: Union[str, None] = "63daa3c4351e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hosting", sa.Column("name", sa.String(length=100), nullable=True))
    
    op.execute("UPDATE hosting SET name = 'hosting-' || id WHERE name IS NULL")
    
    op.alter_column("hosting", "name", nullable=False)
    
    hostingstatus_enum = sa.Enum(
        "CREATING", "RUNNING", "STOPPING", "STOPPED", "ERROR", name="hostingstatus"
    )
    hostingstatus_enum.create(op.get_bind(), checkfirst=True)
    
    op.execute("ALTER TABLE hosting ALTER COLUMN status TYPE hostingstatus USING status::hostingstatus")
    
    op.drop_constraint("hosting_user_id_key", "hosting", type_="unique")
    op.drop_constraint("hosting_vm_id_key", "hosting", type_="unique")
    op.create_index(op.f("ix_hosting_name"), "hosting", ["name"], unique=False)
    op.create_index(op.f("ix_hosting_user_id"), "hosting", ["user_id"], unique=False)
    op.drop_constraint("users_email_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_index(op.f("ix_hosting_user_id"), table_name="hosting")
    op.drop_index(op.f("ix_hosting_name"), table_name="hosting")
    op.create_unique_constraint("hosting_vm_id_key", "hosting", ["vm_id"])
    op.create_unique_constraint("hosting_user_id_key", "hosting", ["user_id"])
    
    # status 컬럼을 VARCHAR로 되돌리기
    op.execute("ALTER TABLE hosting ALTER COLUMN status TYPE VARCHAR(20)")
    
    # enum 타입 삭제
    op.execute("DROP TYPE hostingstatus")
    
    op.drop_column("hosting", "name")
    # ### end Alembic commands ###
